# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'git@github.com:iOSDevelopShareTeam/DSTSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'DSTBaseDevUtils', :path => '../'
  # 加载部分需要的submoudle
#  pod 'DSTBaseDevUtils/DSTUIKit/DSTButton'
  # Pods for Example

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
